apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: node-express-test
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: node-express-test
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/aletor92/node-express-test.git
